### PR TITLE
Feature/add custom shimname to flatpak command

### PR DESCRIPTION
**Pull request by adrianPrestamo**
### Refactor and Enhance flatpak-gen-shims Script

**Changes:**

**Improved Script Structure:**
- Changed the shebang to `#!/usr/bin/env bash` for better portability.
- Added `SCRIPT_DIR` and `CONFIG_DIR` variables to determine and manage the configuration file location more robustly.

**Configuration File Handling:**
- Implemented `ensure_config_file` function to create the configuration file if it does not exist, ensuring smoother setup.
- Introduced `load_config` function to read custom command mappings from the configuration file and populate the `custom_commands` associative array.

**Custom Command Management:**
- Added `add_mapping` function to handle adding or updating custom command mappings in the configuration file.
- Added support for custom command mappings to override default application commands.

**Help Message Enhancement:**
- Added `show_help` function with usage instructions and examples, including a specific example for adding a custom command (e.g., `com.discordapp.Discord` mapped to `discord`).

**Script Main Flow:**
- Updated the main script logic to handle `--add` and `--help` options and integrate new functionalities.
- Improved logging to provide clearer feedback on operations being performed.

**Usage Example:**
- To add or update a custom command mapping: `flatpak-gen-shims --add com.discordapp.Discord discord`
- To display help and usage instructions: `flatpak-gen-shims --help`

**Benefits:**
- Provides more flexibility with custom commands.
- Adds clarity to script functionality and usage.
- Improves robustness in handling configuration files and command mappings.

### CODE REVIEW

**Comment by adrianPrestamo** [comment]
I am sorry if i set up something wrong with Github. I didn't know if I should pull request to develop or master. This is my first contribution to any open source repo

**Comment by ronoaldo** [comment]
Hi @adrianPrestamo thank you for the pull request! I guess that I have an outdated branch called "develop", but you can submit the PR directly to the main branch.

This way it will be easier to identify just your changes. Right now it is a bit confusing. Also, the PR to main should work just fine.

This should be an easy Edit to your pull request, just change the target branch from 'develop' to 'master'

**Comment by adrianPrestamo** [comment]
changed target branch to master

**Comment by ronoaldo** [comment]
OK, this looks awesome! Thank you!

One quick suggestion, if you don't mind: what do you think about having the config outside of the script_root/etc?

Rationale: the etc/ that I have is sort of a "base" that is designed to be linked elsewhere. For instance, my etc/vimrc is sourced by my $HOME/.vimrc, so that changes to the scripts are made only when I plan to publish them.

The current config directory is within source control, so I would recommend either having it ignored by git or reside in XDG_CONFIG_HOME (defaults to $HOME/.config). Toughts?

I tested locally and loved the --add feature!

**Comment by adrianPrestamo** [comment]
Well I have no idea about what is best. Honestly, do as works better for you. 
I opted for the config to be in the script/etc so that is is more portable. 
Thanks for the feedback

**Comment by ronoaldo** [comment]
Perfect! Let's get this merged and afterwards we decide on a best approach. As a quick fix after merge I'll add the file to .gitignore so the portability you intended remains!

LGTM! Thanks again for your contribution, really appreciated!

**Comment by adrianPrestamo** [comment]
Glad it helped, your welcome

**Pull request merged**
